
server:
  port: 8006

spring:
  application:
    name: feign-demo
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-bean-definition-overriding: true





eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10000/eureka/






hystrix:
  command:
    default:
      execution:
        isolation:
          thread :
            timeoutInMilliseconds: 100
ribbon:
  eureka:
    enabled: false
